spring:
  data:
    mongodb:
      authentication-database: "admin"
      host: "localhost"
      database: "test"
      username: "root"
      password: "example"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

